# Конфигурация основной базы данных.
# Если у вас порт не 3306, то указывайте host: "[host]:[port]".
mysql:
  host: localhost
  user: root
  password: "сайнес гпт кодер"
  database: "lite_auction"

# Конфигурация обмена данными.
# Channel - префикс каналов, всего каналов 3 ([channel]_msg, [channel]_sound, [channel]_update).
redis:
  host: localhost
  port: 6379
  password: "сайнес гпт кодер"
  channel: "auction"

# Отвечает за то, что сервер каждые 2.5 секунды будет обновлять лоты.
# А именно делать лоты истекшими и удалять просроченные лоты после 7 дней.
# Включайте это только на 1 сервере, если у вас их несколько.
isHead: true

# Если /ah sell auto не найдет предмет из руки на аукционе,
# то возьмет цену отсюда. (Цена за единицу товара)
default-auto-price: 500

# Провайдер экономики. StickEco или Vault.
economy-editor: StickEco

# Кастомные теги для /ah search
# Сначала то что в поиске, потом тег на который это заменится
# В примере /ah search test покажет все камни на аукционе.
#
# Чтобы понять какие у предмета теги, пишите /ah admin getTags с правами "liteauction.admin"
custom_tags:
  "test": "stone"

# ВАЖНО:
# Файл assets.json НЕ РЕДАКТИРУЙТЕ, так как это может сломать плагин!
# Если вы все-таки хотите поменять название, то меняйте только русский перевод,
# но на ваш страх и риск.

# Написано tg: @Dimasik_v2010 | Студия tg: @StickDev | минки жирный | твайс лев