name: LiteAuction
version: '${project.version}'
main: org.dimasik.liteauction.LiteAuction
api-version: '1.16'
softdepend:
  - StickEco
  - Vault
  - PlaceholderAPI
commands:
  ah:
    aliases:
      - auc
      - auction